version: '3.9' 

services: 
  php: 
    build: 
      dockerfile: Dockerfile 
    volumes: 
      - ./php/src/:/var/www/html/ 
    restart: always 
    ports: 
      - 8000:80 

  db: 
    image: mysql 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: aboba 
      MYSQL_DATABASE: appDB 
    command: ['--default-authentication-plugin=mysql_native_password'] 
    volumes: 
      - db:/var/lib/mysql 
      - ./mysql-init/:/docker-entrypoint-initdb.d/:ro 

volumes:
  db:
